name: Yarn tests

on:
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Run npm tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18.14.0
      - run: yarn install
      - run: yarn test
      - name: Run ESLint
        run: yarn eslint .
      
